baseURL = 'http://0xcyb3rm0nk.github.io/blog/'
languageCode = 'en-us'
title = 'CyberMonk'
theme= 'hugo-PaperMod'
paginate = 5
enableInlineShortcodes = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

[languages.en]
languageName = "English"
weight = 1

[[languages.en.menu.main]]
name = "Archive"
url = "archives"
weight = 5

[[languages.en.menu.main]]
name = "Search"
url = "search/"
weight = 10

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[[languages.en.menu.main]]
name = "Categories"
url = "categories/"
weight = 10

[params.homeInfoParams]
  Title = "NinjaArts of CyberMonk"
  Content = """
Welcome to world of Cyber Ninja's. 
- Here you learn **NinjaArts** of Cyb3rM0nk.
- Knowing the warstories and practicipating in war games will help you grow tough!🌟
"""

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/adityatelange/hugo-PaperMod"

  [[params.socialIcons]]
  name = "KoFi"
  url = "https://ko-fi.com/adityatelange"

  [[params.socialIcons]]
  name = "RsS"
  url = "index.xml"

  [params.editPost]
  URL = "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
  Text = "Suggest Changes"
  appendFilePath = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup.goldmark.renderer]
unsafe = true

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
